# Generated by Django 5.2.5 on 2025-08-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
