# Generated by Django 5.2.5 on 2025-08-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loan_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
